### PR TITLE
fix: Title wrap to prevent offscreen topic labels

### LINKED ISSUE #74: Matplotlib plots text appears outside of bubble
**Describe the bug**
Text appears outside of the bubbles when there are many bubbles with long topic names

**To Reproduce**
Plot a high number of topics (10+)

**Expected behavior**

**Screenshots**
Bubble Chart

**System Information**
Affects all versions.

**Additional Context**

### PR DESCRIPTION
**Pull request by KD-7**
### Reference Issues/PRs

Fixes #74 

### What are the changes/fixes in this PR?

The only feesible way of "working around" the issue without getting into additional complexities is to simply wrap on space.
Alternatively an implementation of this type of graph is possible in Plotly, which could be done in future.

Also fixed matplotlib deprecation warning for cmaps.get_cmap

### CODE REVIEW

**Comment by KD-7** [comment]
> Can we test this approach by adding a test with many topics? Whether this works is unclear based on tests involving only 3 topics.

This is more of a "quick fix ", if the title is long enough and doesnt have enough spacing it will still appear outside of the bubble.

**Comment by yuxqiu** [comment]
> This is more of a "quick fix ", if the title is long enough and doesnt have enough spacing it will still appear outside of the bubble.

So, it doesn't fix #74?

**Comment by KD-7** [comment]
> > This is more of a "quick fix ", if the title is long enough and doesnt have enough spacing it will still appear outside of the bubble.
> 
> So, it doesn't fix #74?

It "kind of does", as we can fit now more bubbles, in my testing before it is about 7 - 10, without them going outside of the bubble. But this again really depends on the length of the topic label. There isn't unfortunately an easy way to scale this, or have automatic wrapping from my understanding.

**Comment by yuxqiu** [comment]
> It "kind of does", as we can fit now more bubbles, in my testing it is about 7 - 10+, without them going outside of the bubble. But this again really depends on the length of the topic label. There isn't unfortunately an easy way to scale this, or have automatic wrapping from my understanding.

It might be worth adding a test case for this. It can inform us if any future changes break what we can achieve now.

**Comment by KD-7** [comment]
> > It "kind of does", as we can fit now more bubbles, in my testing it is about 7 - 10+, without them going outside of the bubble. But this again really depends on the length of the topic label. There isn't unfortunately an easy way to scale this, or have automatic wrapping from my understanding.
> 
> It might be worth adding a test case for this. It can inform us if any future changes break what we can achieve now.

All done, should be good to go!

**Comment by KD-7** [comment]
As a sidenote I wonder whether the word plotter warning is still relevant?

**Review by yuxqiu — APPROVED** [review]

**Comment by yuxqiu** [comment]
> As a sidenote I wonder whether the word plotter warning is still relevant?

Nope. So, I think we can remove it.

**Pull request merged**
