### PR TITLE
Release TrueLearn 1.0.0

### PR DESCRIPTION
**Pull request by KD-7**
### Reference Issues/PRs

N/A
### What are the changes/fixes in this PR?

- [x] Check the documentation on testpypi
- [x] Add a deployments cleaner to clean up our PRs, because our Python publish action creates a huge number of deployments to share secrets between called workflows (due to GitHub API limitations)
- [x] Prepare TrueLearn for release

### CODE REVIEW

**Comment by KD-7** [comment]
> ### Reference Issues/PRs
> N/A
> 
> ### What are the changes/fixes in this PR?
> Prepare TrueLearn for release

Dont merge this yet, I need to bump version number for upload to TestPypi because they dont allow you to overwrite anymore

**Comment by yuxqiu** [comment]
I think it is Kaleido (the backend of Plotly) that causes the suspension of the jobs. If you read the logs for last hanged action, it stopped at testing `savefig` of `PlotlyBasePlotter`. Many reported the same issues:

- https://github.com/plotly/Kaleido/issues/134
- https://github.com/plotly/Kaleido/issues/110

It seems that we can get Kaleido work if we downgrade it to `0.1.0.post1`.

**Comment by KD-7** [comment]
> > > I think it is Kaleido (the backend of Plotly) that causes the suspension of the jobs. If you read the logs for last hanged action, it stopped at testing `savefig` of `PlotlyBasePlotter`. Many reported the same issues:
> > > 
> > > * [write_image hangs plotly/Kaleido#134](https://github.com/plotly/Kaleido/issues/134)
> > > * [Image generation hangs on windows 10 plotly/Kaleido#110](https://github.com/plotly/Kaleido/issues/110)
> > > 
> > > It seems that we can get Kaleido work if we downgrade it to `0.1.0.post1`.
> > 
> > 
> > Is there any functionality we lose from the downgrade?
> 
> Nope. Only the generated files will be slightly different. (Based on [plotly/Kaleido#110 (comment)](https://github.com/plotly/Kaleido/issues/110#issuecomment-1195258978))
> 
> Since we are only testing html and json files, this downgrade will not affect our testing either.

Lets go ahead with it then

**Comment by KD-7** [comment]
> It seems that it hangs again. Probably should downgrade it now.
> 
> Also, I am wondering why there are so many temporarily deployed to testing notification.

Those get all cleared now after the Python Upload Action run finishes by the cleaner action. You see loads of notifications because for each unit test run we have to create a deployment to the `testing` environment so we can access the `Wikifier API token` because called workflows do not have access to tokens (GitHub API restriction)

**Comment by KD-7** [comment]
Looks like it has to be 0.1.0 the post1 doesnt work (does on my local machine oddly enough)

**Comment by yuxqiu** [comment]
It seems that the `0.1.0.post1` version is only for Windows.

**Comment by yuxqiu** [comment]
So, the final `pyproject.toml` should be something like this:

```
# make sure we document this
"kaleido==0.1.0.post1; sys_platform == 'win32'",
"kaleido==0.2.1.post1; sys_platform != 'win32'",
```

**Review by yuxqiu — APPROVED** [review]

**Comment by KD-7** [comment]
I notice that the clean deployments action isnt being called when Upload Python Publish completes even though it should

**Pull request merged**
