### PR TITLE
Update publish action

### PR DESCRIPTION
**Pull request by KD-7**
- [x] Make action deploy to testpypi on release with manual trigger to pypi
- [x] Fix concurrency bugs due to #50 
- [x] Fix unit test bug not detecting user key

### CODE REVIEW

**Comment by KD-7** [comment]
@yuxqiu 
image
Log: https://github.com/TrueLearnAI/truelearn/actions/runs/4548246898/jobs/8019079308
Its failing when the publish action calls it, I think this is to do with the fact that we are doing a workflow call, so the environment may not be the same?

**Comment by yuxqiu** [comment]
I have a question about concurrency. From [Github Doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow-1), it seems that it's unnecessary for us to add a suffix after `group: ${{ github.workflow }}-${{ github.ref }}`. What's the problem that you encountered?

**Comment by yuxqiu** [comment]
> @yuxqiu image Log: https://github.com/TrueLearnAI/truelearn/actions/runs/4548246898/jobs/8019079308 Its failing when the publish action calls it, I think this is to do with the fact that we are doing a workflow call, so the environment may not be the same?

Let me investigate this issue.

**Comment by KD-7** [comment]
> I have a question about concurrency. From [Github Doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow-1), it seems that it's unnecessary for us to add a suffix after `group: ${{ github.workflow }}-${{ github.ref }}`. What's the problem that you encountered?

The problem is if all the workflows are in the same group, they effectively cancel eachother. By appending that text we get the desired behaviour as stated in #50 by assigning each workflow to its own respective group, where currently in-progress runs of the same workflow are cancelled if new commits have been made.

Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time. A concurrency group can be any string or expression. The expression can use any context except for the secrets context. You can also specify concurrency at the workflow level. When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. **To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.**

**Comment by KD-7** [comment]
> > @yuxqiu image Log: https://github.com/TrueLearnAI/truelearn/actions/runs/4548246898/jobs/8019079308 Its failing when the publish action calls it, I think this is to do with the fact that we are doing a workflow call, so the environment may not be the same?
> 
> This thing looks strange because if `WIKIFIER_API_KEY` is `None`, the test would be skipped. However, since it is not skipped here, this means that there is some value in this variable. But based on the output, this is not a valid value.
> 
> So, where does it come from? 😕



> > @yuxqiu image Log: https://github.com/TrueLearnAI/truelearn/actions/runs/4548246898/jobs/8019079308 Its failing when the publish action calls it, I think this is to do with the fact that we are doing a workflow call, so the environment may not be the same?
> 
> This thing looks strange because if `WIKIFIER_API_KEY` is `None`, the test would be skipped. However, since it is not skipped here, this means that there is some value in this variable. But based on the output, this is not a valid value.
> 
> So, where does it come from? 😕

I have found the cause: actions/runner#1490

**Comment by KD-7** [comment]
> > @yuxqiu image Log: https://github.com/TrueLearnAI/truelearn/actions/runs/4548246898/jobs/8019079308 Its failing when the publish action calls it, I think this is to do with the fact that we are doing a workflow call, so the environment may not be the same?
> 
> This thing looks strange because if `WIKIFIER_API_KEY` is `None`, the test would be skipped. However, since it is not skipped here, this means that there is some value in this variable. But based on the output, this is not a valid value.
> 
> So, where does it come from? 😕
Resolved 🚀 , we have this beatiful info about environments on GitHub, but you cant have it all eh

**Comment by yuxqiu** [comment]
> > I have a question about concurrency. From [Github Doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow-1), it seems that it's unnecessary for us to add a suffix after `group: ${{ github.workflow }}-${{ github.ref }}`. What's the problem that you encountered?
> 
> The problem is if all the workflows are in the same group, they effectively cancel eachother. By appending that text we get the desired behaviour as stated in #50 by assigning each workflow to its own respective group, where currently in-progress runs of the same workflow are cancelled if new commits have been made. To see a more precise reason: [immich-app/immich#1820](https://github.com/immich-app/immich/pull/1820) ( We experience a deadlock )
> 
> Concurrency ensures that only a single job or workflow using the same concurrency group will run at a time. A concurrency group can be any string or expression. The expression can use any context except for the secrets context. You can also specify concurrency at the workflow level. When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. **To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.**

I see. So, to solve this problem, we just need to add a suffix to the concurrency group in `python_publish.yml` because it calls other workflows and then the other workflows inherit its `github.workflow`.

But, do you think we need to add suffixes for other workflows? It doesn't seem very necessary except for the sake of consistency.

**Comment by yuxqiu** [comment]
It doesn't seem to work?

**Comment by KD-7** [comment]
> It doesn't seem to work?

yep doesnt work

**Comment by yuxqiu** [comment]
Approved 🚀

**Pull request merged**
